### ISSUE TITLE
nm[host]['osmatch'] does not work

### ISSUE THREAD

**Issue by DoktorByte** [lopes/netbox-scanner#11]
In the function "def scan(self, network):" i get the following error:

"KeyError: 'osmatch'"

For this reason, in the function is the except part called and every host has as Description "unknown host".

Here is a example of the nm[host] variable:

{'hostnames': [{'name': 'XXX', 'type': 'PTR'}], 'addresses': {'ipv4': 'XXX', 'mac': '00:50:56:01:0A:CF'}, 'vendor': {'00:50:56:01:0A:CF': 'VMware'}, 'status': {'state': 'up', 'reason': 'arp-response'}}

We see that there is no Key like osmatch there.

**Comment by lopes** [comment]
In future versions Nmap scan will be completely removed from this script, thus it'll read the Nmap output file in XML and use that information to fill the description field in NetBox. See #18 for more information.
