### ISSUE TITLE
different configs for cron run

### ISSUE THREAD

**Issue by ohobby** [lopes/netbox-scanner#16]
Is it possible to use different configs at different sheduled cron tasks?
Some Networks must scanned often and some less often.

**Comment by ToroNZ** [comment]
Try running it from a cronjob by using a container ?
Perhaps a loop for each config file and mount a different one each time.
```
#!/bin/bash
FILES=/path/to/configs/*
for f in $FILES
do
  echo "Processing $f config file..."
  docker run --rm -ti --user 1000320000 --cap-drop=all -v $f:/root/.netbox-scanner.conf toronz/netbox-scanner-docker:latest
done
```

Source here: https://github.com/ToroNZ/netbox-scanner-container
