### ISSUE TITLE
nmap: duplicated entries detected that I cannot explain

### ISSUE THREAD

**Issue by strus38** [lopes/netbox-scanner#19]
Hi
First thanks for this module, it is really helpful.
I am running it using an nmap ouput, but almost all the entries are detected as 'duplicated' even if I don't have any entry in Netbox before trying to import them.
So are there some cache mechanisms somewhere, or something I should make sure to check to identify the reasons of those duplicates?
Here is the output:

`started: 24 hosts
created: 10.0.2.2/32 "_gateway"
created: 10.0.2.3/32 "autodiscovered:netbox-scanner"
duplicated: 10.0.2.4/32
duplicated: 10.0.2.15/32
duplicated: 10.0.0.1/32
duplicated: 10.0.0.2/32
duplicated: 10.0.0.3/32
duplicated: 10.0.0.4/32
duplicated: 10.0.0.5/32
duplicated: 10.0.0.6/32
duplicated: 10.0.0.9/32
duplicated: 10.0.0.10/32
duplicated: 10.0.0.20/32
duplicated: 10.0.0.220/32
duplicated: 10.0.0.221/32
duplicated: 10.0.0.222/32
duplicated: 10.0.0.253/32
duplicated: 10.0.0.210/32
duplicated: 172.28.128.1/32
duplicated: 172.28.128.2/32
duplicated: 172.28.128.220/32
duplicated: 172.28.128.221/32
duplicated: 172.28.128.222/32
duplicated: 172.28.128.210/32
finished: .0 +2 ~0 -0 !22`

Another question, is that nmap retrieves a lot more info than only IP/hostname, and it seems that the script does take into acccount those extra information. Are there any plan to create automatically the 'vendors', etc ... or would you recommend using another tool, and which one?

thanks.

**Comment by strus38** [comment]
get a newer version of netbox fixed the issue.

**Comment by lopes** [comment]
Good to know the new version have solved your problem. Since Nmap brings too much data, it can be used to compose some kind of device description, but I could not find a way to systematically process such data to create comprehensive descriptors. Let me know if you have any ideas.

**Comment by strus38** [comment]
I guess I will adapt your script to my needs and see what is useful as a PR.
Thanks

Le jeu. 2 juil. 2020 à 20:58, José Lopes <notifications@github.com> a
écrit :
