### ISSUE TITLE
KeyError 

### ISSUE THREAD

**Issue by dudusf04** [lopes/netbox-scanner#21]
Hello Lopes,

I installed the netbox-scanner, but when I run the script, it gives an error.

Maybe because I didn't set it up right.

The error is as follows: 

![2020-09-28_11h34_52](https://user-images.githubusercontent.com/14137948/94423402-7d073c80-0180-11eb-9094-7317d6612d01.png)

Please, can anyone help me.

**Comment by cubiclemonkey** [comment]
I'm getting a similar error. I noticed in the ../tests folder that _run_tests.sh_ might be calling a different python version:

![image](https://user-images.githubusercontent.com/2401274/94839721-61e93680-03e5-11eb-8869-bef38c6ca03b.png)

I changed it to _python3_ and got a different set of errors entirely:

![image](https://user-images.githubusercontent.com/2401274/94839780-79282400-03e5-11eb-8b19-bb808e14dcd8.png)

**Comment by lopes** [comment]
@dudusf04 The README is clear: supported versions are Python v3.7+. You're using v3.6.

@cubiclemonkey In my development environment, I use Python 3 as default. Guess your `python` command is pointing to Python 2 or some older version (< 3.7). Check it out.
